### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by Gattoartico** [Zathrox/Explorercraft#52]
The server crashes on startup, this was on a cubedhost server on 1.16.5, forge 36.2.8, and a number of other mods. Loading with just Explorercraft produces the same issue about as far as I can tell.

These are the latest and the crashlog with only Explorercraft, felt they might be easier to read.
added debug

[latest.log](https://github.com/Zathrox/Explorercraft/files/7450593/latest.log)
[crash-2021-11-01_03.22.07-fml.txt](https://github.com/Zathrox/Explorercraft/files/7450594/crash-2021-11-01_03.22.07-fml.txt)
[debug.log](https://github.com/Zathrox/Explorercraft/files/7450624/debug.log)

**Comment by Zathrox** [comment]
I released a new version of the mod, yesterday afternoon, can you tell me if that mod also has the same issues?

**Comment by Gattoartico** [comment]
It was the latest version, 5.0.5

**Comment by Elfinlocks** [comment]
Is this issue still persisting?

**Comment by Elfinlocks** [comment]
I've tested independently, and can confirm this still happens. This error is because Forge recognizes ExplorerCraft as a client-side only mod. Please fix this because without this adjustment, this mod cannot be used on dedicated servers.

**Comment by Elfinlocks** [comment]
I've seen this issue fixed in some other mods, here are the commits that were used for them in case they're helpful:

https://github.com/lazyMods/RandomFluidCows/commit/5bb0e502f250a21b6807f18057091d1e765bc0f0#

https://github.com/gigaherz/signbutton/commit/f18748e48071efb54377867f762e262a3a7d32ff

**Comment by Zathrox** [comment]
Version 5.0.6 should solve this issue! Thanks very much for the assistance!
